topic_list=[
'infobesity',
'information overload',
'hijacking our minds',
'control the algorithm',
'media mental health',
'social media mental health',
'news anxiety mental health',
'better information diet',
'quantify your media diet',
'quantify your news diet',
'information pollution',
'future of education self-directed',
'future of work self-directed learning',
'Social media impact on mental health',
'a more informed society',
'fighting misinformation society technology',
'Social media toxic',
'News fatigue',
'Disinformation democracy',
'social media driving polarization',
'better content consumption habits',
'impact of attention economy on society',
'attention deficit society technology']